name: go_lazy_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

workspace:
  - packages/common
  - packages/database
  - features/user


dependencies:
  common:
    path: packages/common
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.2.2
  dart_jsonwebtoken: ^3.2.0
  database:
    path: packages/database
  user:
    path: features/user
  uuid: ^4.5.1

dev_dependencies:
  dart_frog_lint: ^0.1.0
  melos: ^7.2.0
  mocktail: ^1.0.3
  test: ^1.25.5



melos:
  useRootAsPackage: true

  scripts:
    build_runner:build:
      description: Run build_runner build on all packages
      run: melos exec --depends-on="build_runner" -- dart run build_runner build
        --delete-conflicting-outputs

    build_runner:watch:
      description: Run build_runner in watch mode
      run: melos exec --depends-on="build_runner" -- dart run build_runner watch
        --delete-conflicting-outputs

    build_runner:clean:
      description: Clean build_runner generated files
      run: melos exec --depends-on="build_runner" -- dart run build_runner clean

    start_server:
      description: Start the Dart Frog server
      run: dart_frog dev
      packageFilters:
        scope: go_lazy_api

    start:
      description: Start the Dart Frog server
      steps:
        - dotenv -e .env.dev -e .env.local -- melos run start_server

    start:prod:
      description: Start the Dart Frog server
      steps:
        - dotenv -e .env.prod -e .env.local -- melos run start_server

    generate:translations:
      run: dart run packages/common/tool/generate_translations.dart
      description: Generate type-safe translation classes from JSON files

    test:
      description: Run tests for every package with a test directory
      run: melos exec --dir-exists="test" -- dart test