name: group
description: Group feature module
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  common:
    path: ../../packages/common
  dart_frog: ^1.1.0
  database:
    path: ../../packages/database
  drift: ^2.4.0
  user:
    path: ../user
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
