// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_translations.dart

class Translations {
  const Translations(this.locale);

  final String locale;

  String get cannotRemoveOwner {
    switch (locale) {
      case 'en': return 'Cannot remove the group owner';
      case 'ar': return 'لا يمكن إزالة مالك المجموعة';
      default: return 'cannot_remove_owner';
    }
  }

  String get groupAlreadyExists {
    switch (locale) {
      case 'en': return 'Group already exists';
      case 'ar': return 'المجموعة موجودة بالفعل';
      default: return 'group_already_exists';
    }
  }

  String get groupNotFound {
    switch (locale) {
      case 'en': return 'Group not found';
      case 'ar': return 'المجموعة غير موجودة';
      default: return 'group_not_found';
    }
  }

  String get insufficientPermissions {
    switch (locale) {
      case 'en': return 'Insufficient permissions';
      case 'ar': return 'صلاحيات غير كافية';
      default: return 'insufficient_permissions';
    }
  }

  String get internalServerError {
    switch (locale) {
      case 'en': return 'Internal server error';
      case 'ar': return 'خطأ داخلي في الخادم';
      default: return 'internal_server_error';
    }
  }

  String get invalidOtp {
    switch (locale) {
      case 'en': return 'Invalid OTP';
      case 'ar': return 'رمز التحقق غير صحيح';
      default: return 'invalid_otp';
    }
  }

  String get notGroupMember {
    switch (locale) {
      case 'en': return 'You are not a member of this group';
      case 'ar': return 'أنت لست عضوًا في هذه المجموعة';
      default: return 'not_group_member';
    }
  }

  String get otpSentEmail {
    switch (locale) {
      case 'en': return 'OTP sent to email';
      case 'ar': return 'تم إرسال رمز التحقق إلى البريد الإلكتروني';
      default: return 'otp_sent_email';
    }
  }

  String get otpSentPhone {
    switch (locale) {
      case 'en': return 'OTP sent to phone number';
      case 'ar': return 'تم إرسال رمز التحقق إلى رقم الهاتف';
      default: return 'otp_sent_phone';
    }
  }

  String get userAlreadyExists {
    switch (locale) {
      case 'en': return 'User already exists';
      case 'ar': return 'المستخدم موجود بالفعل';
      default: return 'user_already_exists';
    }
  }

  String get userNotFound {
    switch (locale) {
      case 'en': return 'User not found';
      case 'ar': return 'المستخدم غير موجود';
      default: return 'user_not_found';
    }
  }

}

const supportedLocales = [
  'en',
  'ar',
];
