// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_translations.dart

class Translations {
  const Translations(this.locale);

  final String locale;

  String get invalidOtp {
    switch (locale) {
      case 'en': return 'Invalid OTP';
      case 'ar': return 'رمز التحقق غير صحيح';
      default: return 'invalid_otp';
    }
  }

  String get otpSentEmail {
    switch (locale) {
      case 'en': return 'OTP sent to email';
      case 'ar': return 'تم إرسال رمز التحقق إلى البريد الإلكتروني';
      default: return 'otp_sent_email';
    }
  }

  String get otpSentPhone {
    switch (locale) {
      case 'en': return 'OTP sent to phone number';
      case 'ar': return 'تم إرسال رمز التحقق إلى رقم الهاتف';
      default: return 'otp_sent_phone';
    }
  }

  String get userAlreadyExists {
    switch (locale) {
      case 'en': return 'User already exists';
      case 'ar': return 'المستخدم موجود بالفعل';
      default: return 'user_already_exists';
    }
  }

  String get userNotFound {
    switch (locale) {
      case 'en': return 'User not found';
      case 'ar': return 'المستخدم غير موجود';
      default: return 'user_not_found';
    }
  }

}

const supportedLocales = [
  'en',
  'ar',
];
