// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_translations.dart

// ignore_for_file: lines_longer_than_80_chars

class Translations {
  const Translations(this.locale);

  final String locale;

  String get accessDenied {
    switch (locale) {
      case 'en':
        return 'Access denied';
      case 'ar':
        return 'تم رفض الوصول';
      default:
        return 'access_denied';
    }
  }

  String get cannotMakeSharedTaskPrivate {
    switch (locale) {
      case 'en':
        return 'Cannot make shared task private after it has been shared with participants';
      case 'ar':
        return 'لا يمكن جعل المهمة المشتركة خاصة بعد مشاركتها مع المشاركين';
      default:
        return 'cannot_make_shared_task_private';
    }
  }

  String get cannotRemoveOwner {
    switch (locale) {
      case 'en':
        return 'Cannot remove the group owner';
      case 'ar':
        return 'لا يمكن إزالة مالك المجموعة';
      default:
        return 'cannot_remove_owner';
    }
  }

  String get goReminderCreated {
    switch (locale) {
      case 'en':
        return 'Reminder set';
      case 'ar':
        return 'تم تعيين التذكير';
      default:
        return 'goReminderCreated';
    }
  }

  String get goReminderDeleted {
    switch (locale) {
      case 'en':
        return 'Reminder deleted';
      case 'ar':
        return 'تم حذف التذكير';
      default:
        return 'goReminderDeleted';
    }
  }

  String get goReminderNotFound {
    switch (locale) {
      case 'en':
        return 'Reminder not found';
      case 'ar':
        return 'التذكير غير موجود';
      default:
        return 'goReminderNotFound';
    }
  }

  String get goReminderUpdated {
    switch (locale) {
      case 'en':
        return 'Reminder updated';
      case 'ar':
        return 'تم تحديث التذكير';
      default:
        return 'goReminderUpdated';
    }
  }

  String get goTaskNotAssignedToYou {
    switch (locale) {
      case 'en':
        return 'This task is not assigned to you';
      case 'ar':
        return 'هذه المهمة غير مخصصة لك';
      default:
        return 'goTaskNotAssignedToYou';
    }
  }

  String get goTaskNotFound {
    switch (locale) {
      case 'en':
        return 'Task not found';
      case 'ar':
        return 'المهمة غير موجودة';
      default:
        return 'goTaskNotFound';
    }
  }

  String get groupAlreadyExists {
    switch (locale) {
      case 'en':
        return 'Group already exists';
      case 'ar':
        return 'المجموعة موجودة بالفعل';
      default:
        return 'group_already_exists';
    }
  }

  String get groupNotFound {
    switch (locale) {
      case 'en':
        return 'Group not found';
      case 'ar':
        return 'المجموعة غير موجودة';
      default:
        return 'group_not_found';
    }
  }

  String get insufficientPermissions {
    switch (locale) {
      case 'en':
        return 'Insufficient permissions';
      case 'ar':
        return 'صلاحيات غير كافية';
      default:
        return 'insufficient_permissions';
    }
  }

  String get internalServerError {
    switch (locale) {
      case 'en':
        return 'Internal server error';
      case 'ar':
        return 'خطأ في الخادم الداخلي';
      default:
        return 'internal_server_error';
    }
  }

  String get invalidOtp {
    switch (locale) {
      case 'en':
        return 'Invalid OTP';
      case 'ar':
        return 'رمز التحقق غير صحيح';
      default:
        return 'invalid_otp';
    }
  }

  String get mustBeParticipantToCreate {
    switch (locale) {
      case 'en':
        return 'You must be a participant to create tasks';
      case 'ar':
        return 'يجب أن تكون مشاركاً لإنشاء المهام';
      default:
        return 'must_be_participant_to_create';
    }
  }

  String get mustBeParticipantToView {
    switch (locale) {
      case 'en':
        return 'You must be a participant to view tasks';
      case 'ar':
        return 'يجب أن تكون مشاركاً لعرض المهام';
      default:
        return 'must_be_participant_to_view';
    }
  }

  String get notGroupMember {
    switch (locale) {
      case 'en':
        return 'You are not a member of this group';
      case 'ar':
        return 'أنت لست عضواً في هذه المجموعة';
      default:
        return 'not_group_member';
    }
  }

  String get otpSentEmail {
    switch (locale) {
      case 'en':
        return 'OTP sent to email';
      case 'ar':
        return 'تم إرسال رمز التحقق إلى البريد الإلكتروني';
      default:
        return 'otp_sent_email';
    }
  }

  String get otpSentPhone {
    switch (locale) {
      case 'en':
        return 'OTP sent to phone number';
      case 'ar':
        return 'تم إرسال رمز التحقق إلى رقم الهاتف';
      default:
        return 'otp_sent_phone';
    }
  }

  String get taskNotFound {
    switch (locale) {
      case 'en':
        return 'Task not found';
      case 'ar':
        return 'المهمة غير موجودة';
      default:
        return 'task_not_found';
    }
  }

  String get userAlreadyExists {
    switch (locale) {
      case 'en':
        return 'User already exists';
      case 'ar':
        return 'المستخدم موجود بالفعل';
      default:
        return 'user_already_exists';
    }
  }

  String get userNotFound {
    switch (locale) {
      case 'en':
        return 'User not found';
      case 'ar':
        return 'المستخدم غير موجود';
      default:
        return 'user_not_found';
    }
  }
}

const supportedLocales = [
  'en',
  'ar',
];
