import 'dart:convert';
import 'dart:developer';
import 'dart:io';

void main() {
  log('Generating translations...');

  final translationsDir = Directory('packages/common/assets/translations');
  final outputFile =
      File('packages/common/lib/src/localization/translations.g.dart');

  if (!translationsDir.existsSync()) {
    log('Error: translations directory not found');
    exit(1);
  }

  final translations = <String, Map<String, String>>{};
  final allKeys = <String>{};

  // Read all JSON translation files
  for (final file in translationsDir.listSync()) {
    if (file is File && file.path.endsWith('.json')) {
      final locale = file.path.split('/').last.replaceAll('.json', '');
      final content = file.readAsStringSync();
      final json = jsonDecode(content) as Map<String, dynamic>;

      translations[locale] =
          json.map((key, value) => MapEntry(key, value as String));
      allKeys.addAll(json.keys);

      log('Loaded $locale: ${json.length} keys');
    }
  }

  if (translations.isEmpty) {
    log('Error: No translation files found');
    exit(1);
  }

  // Generate Dart code
  final buffer = StringBuffer()

    // File header
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('// Generated by tool/generate_translations.dart')
    ..writeln()

    // Translations class
    ..writeln('class Translations {')
    ..writeln('  const Translations(this.locale);')
    ..writeln()
    ..writeln('  final String locale;')
    ..writeln();

  // Generate getter methods for each key
  final sortedKeys = allKeys.toList()..sort();
  for (final key in sortedKeys) {
    final methodName = _toCamelCase(key);
    buffer
      ..writeln('  String get $methodName {')
      ..writeln('    switch (locale) {');

    for (final locale in translations.keys) {
      final value = translations[locale]![key];
      if (value != null) {
        final escapedValue =
            value.replaceAll("'", r"\'").replaceAll('\n', r'\n');
        buffer.writeln("      case '$locale': return '$escapedValue';");
      }
    }

    // Fallback to key if not found
    buffer
      ..writeln("      default: return '$key';")
      ..writeln('    }')
      ..writeln('  }')
      ..writeln();
  }

  buffer
    ..writeln('}')
    ..writeln()
    ..writeln('const supportedLocales = [');

  for (final locale in translations.keys) {
    buffer.writeln("  '$locale',");
  }
  buffer.writeln('];');

  // Write to file
  outputFile.writeAsStringSync(buffer.toString());

  log('✓ Generated ${outputFile.path}');
  log('✓ Created ${sortedKeys.length} translation getters');
  log('✓ Supported locales: ${translations.keys.join(", ")}');
}

String _toCamelCase(String input) {
  final parts = input.split('_');
  if (parts.isEmpty) return input;

  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}
